### PR TITLE
Jack 396 drupal behavior mod 2

### PR DESCRIPTION
**Pull request by sherakama**
# READY

### CODE REVIEW

**Comment by boznik** [comment]
@sherakama  currently the icons need to be placed in the files dir. should this be part of the webpack build?

**Comment by sherakama** [comment]
Webpack can handle your assets. There is handling in the webpack config for it. Is there something, in particular, that is needed that isn't happening?

**Comment by boznik** [comment]
i am going to merge this pr and change the assets path in another topic branch

**Review by boznik — APPROVED** [review]
This is working now. the assets path needs modified but i will do that in another pr

**Pull request merged**
