### PR TITLE
D8CORE-1385: initial commit for news node

### PR DESCRIPTION
**Pull request by jenbreese**
hi @boznik, Can you take a look at this?  It is my first pass at the node page. I don't think it is ready for prime time but I'd like to have it looked at before I go much further. Thanks, Jen

### CODE REVIEW

**Comment by jenbreese** [comment]
Not ready for integration.

**Comment by sherakama** [comment]
You may want to pull in JACK-396-drupal-behavior-mod-2

**Comment by jenbreese** [comment]
> You may want to pull in JACK-396-drupal-behavior-mod-2

Yup! Just did. Thank you!

**Comment by jenbreese** [comment]
# READY FOR REVIEW

# Summary
- Theming for the news node.

# Review Needed By (Date)
- Soonish

# Urgency
- high

# Steps to Test

1. Pull this branch. 
2. Clear cache.
3. Review a news page and verify it looks like the design.

# Affected Projects or Products
- SOE accelerant 

# Associated Issues and/or People
- D8CORE-1385

- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- @boznik 
- @sherakama

**Review by boznik — APPROVED** [review]
This is working as expected.

**Pull request merged**
